package cn.yunzhisheng.vui.assistant.tv.view;


public enum VoiceMode {
	MODE_DEFAULT,
	MODE_UNAVILIABLE,
	MODE_RECORDINGINIT,
    MODE_RECORDING,
    MODE_RECOGNISING,
    MODE_UNRECOGNISED,
    MODE_PROTOCAL,
    MODE_RECORDINGSHORT,
    MODE_NO_VOICE;
}